contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #mydemo channel"
    url: https://nfcore.slack.com/channels/mydemo
    about: Discussion about the nf-core/mydemo pipeline
